# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Perfect FIT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Perfect FIT

    pod 'Alamofire', '~> 4.5.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'Kingfisher', '~> 3.10.3'
    pod 'XLPagerTabStrip', '~> 7.0'
    pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
    pod 'SwiftEventBus', :tag => '2.2.0', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
    pod 'Fabric'
    pod 'Crashlytics'

end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end
